In [ ]:
import pandas as pd
import ast

In [ ]:
# Load dataset
df = pd.read_csv('/content/TomLembong-praprepo1.csv')

In [ ]:
kamus = pd.read_csv('/content/full_lexicon.csv')

In [ ]:
print(kamus.columns)
print(df.columns)

Index(['word', 'weight', 'number_of_words'], dtype='object')
Index(['publishedAt', 'authorDisplayName', 'textDisplay', 'likeCount',
       'clean_text'],
      dtype='object')

In [ ]:
sentimen_dict = dict(zip(kamus['word'], kamus['weight']))

In [ ]:
import nltk

In [ ]:
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [ ]:
df = df.dropna()

In [ ]:
df.head()

,publishedAt,authorDisplayName,textDisplay,likeCount,clean_text
0,2025-08-01T14:49:47Z,@ferryirwandi,Hallo warga sipil sekalian! jadi cemana menuru...,524,hallo tidak sipil sekali cemana kalian
1,2025-08-01T14:53:42Z,@MFDOfficialChannel,"Strategi politik, basi",43,strategi politik basi
2,2025-08-01T14:55:39Z,@Frenysf,"Labil, plinpan, basi, dan ah sudahlah",28,labil plinpan basi ah
3,2025-08-01T14:59:40Z,@fathurrajli2495,"Ya, begitulah!",6,begitu
4,2025-08-01T14:59:59Z,@AntiPembodohan,Hanya TOM seorang yg layak mengapresiasi aboli...,27,tom orang layak tidak abolisi tidak siapa tom ...

In [ ]:
# Tokenisasi ulang untuk kolom 'final_cleaned_text' (jika belum tokenized)
from nltk.tokenize import word_tokenize

df['clean_text'] = df['clean_text'].fillna('').astype(str)
df['tokens'] = df['clean_text'].apply(word_tokenize)

# Sekarang kolom 'tokens' sudah bisa langsung digunakan tanpa literal_eval
print(df['tokens'].head())

0        [hallo, tidak, sipil, sekali, cemana, kalian]
1                            [strategi, politik, basi]
2                           [labil, plinpan, basi, ah]
3                                             [begitu]
4    [tom, orang, layak, tidak, abolisi, tidak, sia...
Name: tokens, dtype: object

In [ ]:
print(df.columns)

Index(['publishedAt', 'authorDisplayName', 'textDisplay', 'likeCount',
       'clean_text', 'tokens'],
      dtype='object')

In [ ]:
def hitung_skor_dan_label(tokens):
    total_skor = sum(sentimen_dict.get(token.lower(), 0) for token in tokens)
    if total_skor > 0:
        label = 'positif'
    elif total_skor < 0:
        label = 'negatif'
    else:
        label = 'netral'
    return pd.Series([total_skor, label])

In [ ]:
df[['skor_total', 'sentimen']] = df['tokens'].apply(hitung_skor_dan_label)

In [ ]:
df.head()

,publishedAt,authorDisplayName,textDisplay,likeCount,clean_text,tokens,skor_total,sentimen
0,2025-08-01T14:49:47Z,@ferryirwandi,Hallo warga sipil sekalian! jadi cemana menuru...,524,hallo tidak sipil sekali cemana kalian,"[hallo, tidak, sipil, sekali, cemana, kalian]",-2,negatif
1,2025-08-01T14:53:42Z,@MFDOfficialChannel,"Strategi politik, basi",43,strategi politik basi,"[strategi, politik, basi]",-6,negatif
2,2025-08-01T14:55:39Z,@Frenysf,"Labil, plinpan, basi, dan ah sudahlah",28,labil plinpan basi ah,"[labil, plinpan, basi, ah]",-9,negatif
3,2025-08-01T14:59:40Z,@fathurrajli2495,"Ya, begitulah!",6,begitu,[begitu],0,netral
4,2025-08-01T14:59:59Z,@AntiPembodohan,Hanya TOM seorang yg layak mengapresiasi aboli...,27,tom orang layak tidak abolisi tidak siapa tom ...,"[tom, orang, layak, tidak, abolisi, tidak, sia...",-48,negatif

In [ ]:
df.drop(['publishedAt', 'authorDisplayName', 'likeCount', 'textDisplay', 'tokens', 'skor_total'], axis=1, inplace=True)

In [ ]:
df.head()

                                          clean_text sentimen
0             hallo tidak sipil sekali cemana kalian  negatif
1                              strategi politik basi  negatif
2                              labil plinpan basi ah  negatif
3                                             begitu   netral
4  tom orang layak tidak abolisi tidak siapa tom ...  negatif

In [ ]:
df.rename(columns={'clean_text': 'textDisplay'}, inplace=True)
df.head()

                                         textDisplay sentimen
0             hallo tidak sipil sekali cemana kalian  negatif
1                              strategi politik basi  negatif
2                              labil plinpan basi ah  negatif
3                                             begitu   netral
4  tom orang layak tidak abolisi tidak siapa tom ...  negatif

In [ ]:
df.to_csv('TomLem.csv', index=False)
print("\nHasil disimpan ke 'output_sentimen.csv'")

Hasil disimpan ke 'output_sentimen.csv'